//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInfo
    {
        public int NO { get; set; }
        public string CarType { get; set; }
        public string EmployeeID { get; set; }
        public string ID { get; set; }
        public string ERP_ID { get; set; }
        public string Year { get; set; }
        public string TradeMark { get; set; }
        public string PlateNO { get; set; }
        public string ContractID { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string EngineNO { get; set; }
        public Nullable<int> FuelUseTax { get; set; }
        public Nullable<int> LicenseTax { get; set; }
        public string Remark { get; set; }
        public string CR_USER { get; set; }
        public Nullable<System.DateTime> CR_DATE { get; set; }
        public string USERSTAMP { get; set; }
        public Nullable<System.DateTime> DATESTAMP { get; set; }
    }
}
