//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0005
    {
        public int ID { get; set; }
        public string MODT { get; set; }
        public string ALIAS { get; set; }
        public string CODET { get; set; }
        public string CODETS { get; set; }
        public string DSC1 { get; set; }
        public string DSC2 { get; set; }
        public string RMK { get; set; }
        public Nullable<int> COSO { get; set; }
        public string RE1 { get; set; }
        public string RE2 { get; set; }
        public Nullable<int> RE3 { get; set; }
        public Nullable<int> RE4 { get; set; }
        public Nullable<System.DateTime> RE5 { get; set; }
        public Nullable<System.DateTime> RE6 { get; set; }
        public string CR_USER { get; set; }
        public Nullable<System.DateTime> CR_DATE { get; set; }
        public string AP_USER { get; set; }
        public Nullable<System.DateTime> AP_DATE { get; set; }
        public string UP_USER { get; set; }
        public Nullable<System.DateTime> UP_DATE { get; set; }
    }
}
