//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F4501
    {
        public int ID { get; set; }
        public string Comp_Cde { get; set; }
        public string Nature { get; set; }
        public string NO { get; set; }
        public string Year { get; set; }
        public string CType { get; set; }
        public string Target { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<System.DateTime> StrDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CAmt { get; set; }
        public string CRNo { get; set; }
        public string CName { get; set; }
        public string CContent { get; set; }
        public string Remark { get; set; }
        public string Sales { get; set; }
        public string CPIC { get; set; }
        public string OCPIC { get; set; }
        public string CDept { get; set; }
        public string Classified { get; set; }
        public string First { get; set; }
        public string BPMNo { get; set; }
        public string CtypeOther { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> ADate { get; set; }
        public Nullable<int> AEID { get; set; }
        public string ASAPID { get; set; }
        public string ATitle { get; set; }
        public string AAccount { get; set; }
        public string ADept { get; set; }
        public string ADeptID { get; set; }
        public string APC { get; set; }
        public string ACC { get; set; }
        public string AWP { get; set; }
        public Nullable<int> FEID { get; set; }
        public string FSAPID { get; set; }
        public string FTitle { get; set; }
        public string FAccount { get; set; }
        public string FDept { get; set; }
        public string FDeptID { get; set; }
        public string FPC { get; set; }
        public string FCC { get; set; }
        public string FWP { get; set; }
        public string AppType { get; set; }
        public string BS { get; set; }
        public string SS { get; set; }
        public string Sign { get; set; }
        public string OS { get; set; }
        public string SP { get; set; }
        public string CS { get; set; }
        public string IDCard { get; set; }
        public string Pts { get; set; }
        public string CSD { get; set; }
        public string BC { get; set; }
        public string CP { get; set; }
        public string FO { get; set; }
        public string DP { get; set; }
        public string DPlace { get; set; }
        public Nullable<System.DateTime> Extend { get; set; }
        public string WP { get; set; }
        public string CounterSign { get; set; }
        public Nullable<int> TaxAmt { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string ECSApplyNo { get; set; }
        public string CVR { get; set; }
        public string UploadFiles { get; set; }
        public string Vendor { get; set; }
        public string CR_USER { get; set; }
        public Nullable<System.DateTime> CR_DATE { get; set; }
        public string USERSTAMP { get; set; }
        public Nullable<System.DateTime> DATESTAMP { get; set; }
        public string CrmOppNo { get; set; }
        public string BILLABLE_TIME { get; set; }
        public string ERP_ASSID { get; set; }
    }
}
