//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MART_AnalyseRevenueAll
    {
        public string DeptID { get; set; }
        public string Comp { get; set; }
        public string DeptCenter { get; set; }
        public string DeptDivision { get; set; }
        public string DeptDepartment { get; set; }
        public string DeptSection { get; set; }
        public string ProfitCenter { get; set; }
        public string Employee { get; set; }
        public string EmployeeID { get; set; }
        public string Phase { get; set; }
        public string DocNo { get; set; }
        public string InternalNo { get; set; }
        public string project { get; set; }
        public string OppNo { get; set; }
        public string SOType { get; set; }
        public string COInvoiceNo { get; set; }
        public string COInvoiceItem { get; set; }
        public string COSONo { get; set; }
        public string COSOItem { get; set; }
        public string InvoiceNumber { get; set; }
        public string RenewStatus { get; set; }
        public Nullable<System.DateTime> MaterialAvailableDate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string YearMonth { get; set; }
        public string CustomerID { get; set; }
        public string Customer { get; set; }
        public string Location { get; set; }
        public string ProdID { get; set; }
        public string Product { get; set; }
        public string POWarranty { get; set; }
        public string SOWarranty { get; set; }
        public string ProdHierarchy { get; set; }
        public string ProdHierarchyBrad { get; set; }
        public string DeptAnnualTargetPK { get; set; }
        public string EmpAnnualTargetPK { get; set; }
        public string PMTargetPK { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public System.DateTime InsertTime { get; set; }
    }
}
