//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public string MARA_MATNR { get; set; }
        public string MARD_WERKS { get; set; }
        public string MARD_LGORT { get; set; }
        public string MVKE_VKORG { get; set; }
        public string MVKE_VTWEG { get; set; }
        public string MARA_MFRPN { get; set; }
        public string MAKT_TXZA1_ZF { get; set; }
        public string MAKT_TXZA1_EN { get; set; }
        public string MARA_STXL1 { get; set; }
        public string MARA_STXL2 { get; set; }
        public string MARA_STXL3 { get; set; }
        public string MARA_STXL4 { get; set; }
        public string MVKE_PRODH { get; set; }
        public string MARA_MATKL { get; set; }
        public string StorageBlock { get; set; }
        public string BasicContent { get; set; }
    }
}
