//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MCSWorkflowEntities : DbContext
    {
        public MCSWorkflowEntities()
            : base("name=MCSWorkflowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<TB_SERVICES_APP_STATE> TB_SERVICES_APP_STATE { get; set; }
        public virtual DbSet<TB_SERVICES_APP_INSTALL> TB_SERVICES_APP_INSTALL { get; set; }
        public virtual DbSet<TB_SERVICES_APP_INSTALLTEMP> TB_SERVICES_APP_INSTALLTEMP { get; set; }
        public virtual DbSet<CarInfo> CarInfo { get; set; }
        public virtual DbSet<VIEW_DEPT_MGR> VIEW_DEPT_MGR { get; set; }
        public virtual DbSet<TB_APP_DEVICE_TOKEN> TB_APP_DEVICE_TOKEN { get; set; }
        public virtual DbSet<TB_APP_PUSH_NOTICE_MESSAGES> TB_APP_PUSH_NOTICE_MESSAGES { get; set; }
        public virtual DbSet<VIEW_EMP_INFO> VIEW_EMP_INFO { get; set; }
        public virtual DbSet<TB_APP_INFO> TB_APP_INFO { get; set; }
    }
}
