//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APP_DATAEntities : DbContext
    {
        public APP_DATAEntities()
            : base("name=APP_DATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_SURVEY_ANS_MAINTAIN> TB_SURVEY_ANS_MAINTAIN { get; set; }
        public virtual DbSet<TB_SURVEY_QUS_MAINTAIN> TB_SURVEY_QUS_MAINTAIN { get; set; }
        public virtual DbSet<TB_CAR_CHECKLIST> TB_CAR_CHECKLIST { get; set; }
        public virtual DbSet<TB_CAR_OWNER> TB_CAR_OWNER { get; set; }
        public virtual DbSet<TB_CAR_PHOTOS> TB_CAR_PHOTOS { get; set; }
        public virtual DbSet<TB_CAR_BOOKING> TB_CAR_BOOKING { get; set; }
        public virtual DbSet<TB_CAR_DATA> TB_CAR_DATA { get; set; }
        public virtual DbSet<TB_LIVE_MESSAGE> TB_LIVE_MESSAGE { get; set; }
        public virtual DbSet<TB_LUCKYDRAW> TB_LUCKYDRAW { get; set; }
        public virtual DbSet<TB_LUCKYDRAW_PRIZE> TB_LUCKYDRAW_PRIZE { get; set; }
        public virtual DbSet<TB_ANNIVERSARY_CHECK_IN> TB_ANNIVERSARY_CHECK_IN { get; set; }
        public virtual DbSet<TB_LUCKYDRAW_PRIZEWINNING> TB_LUCKYDRAW_PRIZEWINNING { get; set; }
    }
}
