//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string ID { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public string Name2 { get; set; }
        public string DeptID { get; set; }
        public string TitleID { get; set; }
        public string TitleName { get; set; }
        public int Level { get; set; }
        public int PositionCode { get; set; }
        public string AgentID { get; set; }
        public Nullable<System.DateTime> AgentStartTime { get; set; }
        public Nullable<System.DateTime> AgentEndTime { get; set; }
        public bool Away { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string CostCenter { get; set; }
        public int NotifyType { get; set; }
        public bool Pluralism { get; set; }
        public string PositionCode2 { get; set; }
        public Nullable<bool> Manager { get; set; }
        public Nullable<bool> IsDeptManager { get; set; }
        public int Status { get; set; }
        public string PID { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Constellation { get; set; }
        public string Sex { get; set; }
        public string Job_Status { get; set; }
        public Nullable<System.DateTime> Regest_Date { get; set; }
        public Nullable<System.DateTime> CallIn_Date { get; set; }
        public Nullable<System.DateTime> CallOut_Date { get; set; }
        public Nullable<System.DateTime> Replace_Date { get; set; }
        public Nullable<System.DateTime> Leave_Date { get; set; }
        public string Leave_Reason { get; set; }
        public string Comp_Cde { get; set; }
        public string Area_Cde { get; set; }
        public string Job_Type { get; set; }
        public string Title1 { get; set; }
        public string Title2 { get; set; }
        public string Capital_Position1 { get; set; }
        public string Capital_Position2 { get; set; }
        public Nullable<System.DateTime> Cp_Date { get; set; }
        public string Position1 { get; set; }
        public string Position2 { get; set; }
        public Nullable<System.DateTime> Position_Date { get; set; }
        public string Comp_Phone { get; set; }
        public string Extension { get; set; }
        public string Nationality { get; set; }
        public string Blood_Type { get; set; }
        public string CR_USER { get; set; }
        public System.DateTime CR_DATE { get; set; }
        public string USERSTAMP { get; set; }
        public Nullable<System.DateTime> DATESTAMP { get; set; }
        public string Work_Place { get; set; }
        public string ERP_ID { get; set; }
        public string Workers { get; set; }
        public string Center { get; set; }
        public string Account { get; set; }
    }
}
