//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKALL
    {
        public string IV_SERIAL { get; set; }
        public string IV_VENDOR { get; set; }
        public string IV_VNAME { get; set; }
        public string IV_PONO { get; set; }
        public Nullable<System.DateTime> IV_GRDATE { get; set; }
        public string ProdID { get; set; }
        public string Product { get; set; }
        public string ProdHierarchy { get; set; }
        public string SoNo { get; set; }
        public Nullable<decimal> SoAmount { get; set; }
        public string SoSales { get; set; }
        public string SoSalesName { get; set; }
        public string INTERNALNO { get; set; }
        public Nullable<System.DateTime> IV_DNDATE { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string IV_SLASRV { get; set; }
        public string IV_SLARESP { get; set; }
        public string OppNo { get; set; }
        public string ProjName { get; set; }
        public string VENDOROM_WTYID { get; set; }
        public Nullable<System.DateTime> VENDOROM_SDATE { get; set; }
        public Nullable<System.DateTime> VENDOROM_EDATE { get; set; }
        public string OM_WTYID { get; set; }
        public Nullable<System.DateTime> OM_SDATE { get; set; }
        public Nullable<System.DateTime> OM_EDATE { get; set; }
        public string EX_WTYID { get; set; }
        public Nullable<System.DateTime> EX_SDATE { get; set; }
        public Nullable<System.DateTime> EX_EDATE { get; set; }
        public string TM_WTYID { get; set; }
        public Nullable<System.DateTime> TM_SDATE { get; set; }
        public Nullable<System.DateTime> TM_EDATE { get; set; }
        public string ContractID { get; set; }
        public string ContractName { get; set; }
        public Nullable<System.DateTime> ContractSDATE { get; set; }
        public Nullable<System.DateTime> ContractEDate { get; set; }
        public string RenewStatus { get; set; }
        public Nullable<System.DateTime> CR_DATE { get; set; }
    }
}
