//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKIN
    {
        public string IV_SERIAL { get; set; }
        public string IV_PONO { get; set; }
        public Nullable<System.DateTime> IV_GRDATE { get; set; }
        public string IV_VENDOR { get; set; }
        public string IV_VNAME { get; set; }
        public string IV_MATERIAL { get; set; }
        public string IV_DESC { get; set; }
        public string IV_WTYID { get; set; }
        public string IV_WTYDESC { get; set; }
        public Nullable<System.DateTime> IV_SDATE { get; set; }
        public Nullable<System.DateTime> IV_EDATE { get; set; }
        public string CR_USER { get; set; }
        public Nullable<System.DateTime> CR_DATE { get; set; }
        public string UP_USER { get; set; }
        public Nullable<System.DateTime> UP_DATE { get; set; }
    }
}
