//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CAR_BOOKING
    {
        public int ID { get; set; }
        public string BOOKING_ID { get; set; }
        public string RENT_DATE { get; set; }
        public string START_TIME { get; set; }
        public string END_TIME { get; set; }
        public string USER_NAME { get; set; }
        public string USER_ERPID { get; set; }
        public string FILL_USER_NAME { get; set; }
        public string FILL_USER_ERPID { get; set; }
        public string RENT_REASON { get; set; }
        public string RENT_DESC { get; set; }
        public string DISABLED { get; set; }
        public string OVER_TIME { get; set; }
        public string ENGINE_START_TIME { get; set; }
        public string ENGINE_STOP_TIME { get; set; }
        public string INSERT_TIME { get; set; }
        public string LPN { get; set; }
        public string RENT_STATUS { get; set; }
        public Nullable<decimal> MILEAGE_START { get; set; }
        public string MILEAGE_START_IMG { get; set; }
        public Nullable<decimal> MILEAGE_END { get; set; }
        public string MILEAGE_END_IMG { get; set; }
    }
}
