//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CAR_CHECKLIST
    {
        public int ID { get; set; }
        public string BOOKING_ID { get; set; }
        public string ITEM1 { get; set; }
        public string ITEM2 { get; set; }
        public string ITEM3 { get; set; }
        public string ITEM4 { get; set; }
        public string ITEM5 { get; set; }
        public string ITEM6 { get; set; }
        public string ITEM7 { get; set; }
        public string ITEM8 { get; set; }
        public string ITEM9 { get; set; }
        public string ITEM10 { get; set; }
        public string ITEM11 { get; set; }
        public string ITEM12 { get; set; }
        public string INSERT_USER { get; set; }
        public string INSERT_TIME { get; set; }
        public string Memo { get; set; }
    }
}
