//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LUCKYDRAW_PRIZE
    {
        public int Prize_ID { get; set; }
        public Nullable<int> Draw_ID { get; set; }
        public int Sort_No { get; set; }
        public string Prize_Name { get; set; }
        public string Prize_Pic { get; set; }
        public Nullable<int> Prize_Amount { get; set; }
        public bool OverAYear_Mark { get; set; }
        public Nullable<int> Draw_Amount { get; set; }
        public Nullable<int> Prize_Price { get; set; }
        public string Insert_User { get; set; }
        public string Insert_Time { get; set; }
        public string Modify_User { get; set; }
        public string Modify_Time { get; set; }
        public bool Disabled_Mark { get; set; }
        public string Prize_Memo { get; set; }
    }
}
