//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LUCKYDRAW_PRIZEWINNING
    {
        public int Winning_ID { get; set; }
        public Nullable<int> Prize_ID { get; set; }
        public string User_Name { get; set; }
        public string User_ERPID { get; set; }
        public string Insert_User { get; set; }
        public string Insert_Time { get; set; }
        public string Modify_User { get; set; }
        public string Modify_Time { get; set; }
        public bool Disabled_Mark { get; set; }
        public bool Redeem_Mark { get; set; }
        public string Redeem_Time { get; set; }
        public Nullable<int> Draw_ID { get; set; }
        public bool Donate_Mark { get; set; }
    }
}
