//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ONE_SRMain
    {
        public string cSRID { get; set; }
        public string cCustomerID { get; set; }
        public string cCustomerName { get; set; }
        public string cDesc { get; set; }
        public string cNotes { get; set; }
        public string cAttachement { get; set; }
        public string cAttachementStockNo { get; set; }
        public string cStatus { get; set; }
        public string cMAServiceType { get; set; }
        public string cDelayReason { get; set; }
        public string cSRTypeOne { get; set; }
        public string cSRTypeSec { get; set; }
        public string cSRTypeThr { get; set; }
        public string cSRPathWay { get; set; }
        public string cSRProcessWay { get; set; }
        public string cSRRepairLevel { get; set; }
        public string cIsSecondFix { get; set; }
        public string cIsAPPClose { get; set; }
        public string cIsInternalWork { get; set; }
        public string cRepairName { get; set; }
        public string cRepairAddress { get; set; }
        public string cRepairPhone { get; set; }
        public string cRepairMobile { get; set; }
        public string cRepairEmail { get; set; }
        public string cTeamID { get; set; }
        public string cMainEngineerID { get; set; }
        public string cMainEngineerName { get; set; }
        public string cAssEngineerID { get; set; }
        public string cTechManagerID { get; set; }
        public string cSQPersonID { get; set; }
        public string cSQPersonName { get; set; }
        public string cSalesID { get; set; }
        public string cSalesName { get; set; }
        public string cSecretaryID { get; set; }
        public string cSecretaryName { get; set; }
        public string cSalesNo { get; set; }
        public string cShipmentNo { get; set; }
        public string cContractID { get; set; }
        public Nullable<int> cCountIN { get; set; }
        public Nullable<int> cCountOUT { get; set; }
        public string cFaultGroup { get; set; }
        public string cFaultGroupNote1 { get; set; }
        public string cFaultGroupNote2 { get; set; }
        public string cFaultGroupNote3 { get; set; }
        public string cFaultGroupNote4 { get; set; }
        public string cFaultGroupNoteOther { get; set; }
        public string cFaultState { get; set; }
        public string cFaultStateNote1 { get; set; }
        public string cFaultStateNote2 { get; set; }
        public string cFaultStateNoteOther { get; set; }
        public string cFaultSpec { get; set; }
        public string cFaultSpecNote1 { get; set; }
        public string cFaultSpecNote2 { get; set; }
        public string cFaultSpecNoteOther { get; set; }
        public string cPerCallSLARESP { get; set; }
        public string cPerCallSLASRV { get; set; }
        public string cRemark { get; set; }
        public Nullable<System.Guid> cSystemGUID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUserName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUserName { get; set; }
    }
}
