//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ONE_SRMain
    {
        public string cSRID { get; set; }
        public string cCustomerID { get; set; }
        public string cCustomerName { get; set; }
        public string cDesc { get; set; }
        public string cNotes { get; set; }
        public string cAttatchement { get; set; }
        public string cStatus { get; set; }
        public string cMAServiceType { get; set; }
        public string cDelayReason { get; set; }
        public string cSRTypeOne { get; set; }
        public string cSRTypeSec { get; set; }
        public string cSRTypeThr { get; set; }
        public string cSRPathWay { get; set; }
        public string cSRProcessWay { get; set; }
        public string cIsSecondFix { get; set; }
        public string cRepairName { get; set; }
        public string cContacterName { get; set; }
        public string cContactAddress { get; set; }
        public string cContactPhone { get; set; }
        public string cContactEmail { get; set; }
        public string cTeamID { get; set; }
        public string cMainEngineerID { get; set; }
        public string cMainEngineerName { get; set; }
        public string cAssEngineerID { get; set; }
        public string cSQPersonID { get; set; }
        public string cSQPersonName { get; set; }
        public string cSalesID { get; set; }
        public string cSalesName { get; set; }
        public Nullable<System.Guid> cSystemGUID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUserName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUserName { get; set; }
    }
}
