//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ONE_SRBatchInstallRecord
    {
        public System.Guid cGUID { get; set; }
        public string cSRID { get; set; }
        public string cCustomerID { get; set; }
        public string cCustomerName { get; set; }
        public string cTeamID { get; set; }
        public string cContactName { get; set; }
        public string cContactAddress { get; set; }
        public string cContactPhone { get; set; }
        public string cContactMobile { get; set; }
        public string cContactEmail { get; set; }
        public string cMainEngineerID { get; set; }
        public string cMainEngineerName { get; set; }
        public string cSalesID { get; set; }
        public string cSalesName { get; set; }
        public string cSecretaryID { get; set; }
        public string cSecretaryName { get; set; }
        public string cSalesNo { get; set; }
        public string cShipmentNo { get; set; }
        public string cSerialID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUserName { get; set; }
    }
}
