//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ONE_DOCUMENT
    {
        public System.Guid ID { get; set; }
        public string REF_OBJ_ID { get; set; }
        public string FILE_ORG_NAME { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_EXT { get; set; }
        public string INSERT_TIME { get; set; }
    }
}
