//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ONE_ContractMain
    {
        public string cContractID { get; set; }
        public string cCustomerContractNo { get; set; }
        public string cSoNo { get; set; }
        public string cSoSales { get; set; }
        public string cSoSalesName { get; set; }
        public string cSoSalesASS { get; set; }
        public string cSoSalesASSName { get; set; }
        public string cMASales { get; set; }
        public string cMASalesName { get; set; }
        public string cCustomerID { get; set; }
        public string cCustomerName { get; set; }
        public string cDesc { get; set; }
        public Nullable<System.DateTime> cStartDate { get; set; }
        public Nullable<System.DateTime> cEndDate { get; set; }
        public string cMACycle { get; set; }
        public string cMANotes { get; set; }
        public string cMAAddress { get; set; }
        public string cSLARESP { get; set; }
        public string cSLASRV { get; set; }
        public string cContractNotes { get; set; }
        public string cContractReport { get; set; }
        public string cTeamID { get; set; }
        public string cIsSubContract { get; set; }
        public string cBillCycle { get; set; }
        public string cBillNotes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUserName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUserName { get; set; }
    }
}
