//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ONE_ContractDetail_OBJ
    {
        public int cID { get; set; }
        public string cContractID { get; set; }
        public string cHostName { get; set; }
        public string cSerialID { get; set; }
        public string cPID { get; set; }
        public string cBrands { get; set; }
        public string cModel { get; set; }
        public string cLocation { get; set; }
        public string cAddress { get; set; }
        public string cArea { get; set; }
        public string cSLARESP { get; set; }
        public string cSLASRV { get; set; }
        public string cNotes { get; set; }
        public string cSubContractID { get; set; }
        public Nullable<int> Disabled { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUserName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUserName { get; set; }
    }
}
