//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public System.Guid cEmployee_ID { get; set; }
        public string cEmployee_NO { get; set; }
        public string cEmployee_cName { get; set; }
        public string cEmployee_Ename { get; set; }
        public string cEmployee_Title { get; set; }
        public System.Guid cDepartment_ID { get; set; }
        public int cEmployee_Level { get; set; }
        public Nullable<int> cEmployee_PositionCode { get; set; }
        public string cEmployee_PositionCode2 { get; set; }
        public bool cEmployee_Away { get; set; }
        public string cEmployee_Tel { get; set; }
        public string cEmployee_Mobile { get; set; }
        public string cEmployee_Fax { get; set; }
        public string cEmployee_Email { get; set; }
        public int cEmployee_NotifyTypeID { get; set; }
        public bool cEmployee_Pluralism { get; set; }
        public int cEmployee_Status { get; set; }
        public string cEmployee_PID { get; set; }
        public Nullable<System.DateTime> cEmployee_BrithDay { get; set; }
        public string cEmployee_ConstellationID { get; set; }
        public string cEmployee_PhotoPath { get; set; }
        public string cEmployee_SexID { get; set; }
        public string cEmployee_JobStatusID { get; set; }
        public Nullable<System.DateTime> cEmployee_RegestDate { get; set; }
        public Nullable<System.DateTime> cEmployee_CallInDate { get; set; }
        public Nullable<System.DateTime> cEmployee_CallOutDate { get; set; }
        public Nullable<System.DateTime> cEmployee_ReplaceDate { get; set; }
        public Nullable<System.DateTime> cEmployee_TakeDay { get; set; }
        public Nullable<System.DateTime> cEmployee_LeaveDay { get; set; }
        public string cEmployee_LeaveReason { get; set; }
        public string cEmployee_CompanyCode { get; set; }
        public string cEmployee_AreaCode { get; set; }
        public string cEmployee_JobTypeID { get; set; }
        public string cEmployee_Title1 { get; set; }
        public string cEmployee_Title2 { get; set; }
        public string cEmployee_CapitalPosition1 { get; set; }
        public string cEmployee_CapitalPosition2 { get; set; }
        public Nullable<System.DateTime> cEmployee_CpDate { get; set; }
        public string cEmployee_Position1 { get; set; }
        public string cEmployee_Position2 { get; set; }
        public Nullable<System.DateTime> cEmployee_PositionDate { get; set; }
        public string cEmployee_CompanyPhone { get; set; }
        public string cEmployee_CompanyPhoneExt { get; set; }
        public string cEmployee_NationalityID { get; set; }
        public string cEmployee_BloodType { get; set; }
        public string cEmployee_WorkPlace { get; set; }
        public string cEmployee_ERPID { get; set; }
        public string cEmployee_Workers { get; set; }
        public string cEmployee_Center { get; set; }
        public string cEmployee_Assign_Type { get; set; }
        public bool cEmployee_IsEnable { get; set; }
        public string cEmployee_Account { get; set; }
        public System.DateTime cEmployee_CreateDate { get; set; }
        public System.Guid cEmployee_CreateUser { get; set; }
        public Nullable<System.DateTime> cEmployee_ModifyDate { get; set; }
        public Nullable<System.Guid> cEmployee_ModifyUser { get; set; }
        public string cEmployee_Level1 { get; set; }
        public string cEmployee_Level2 { get; set; }
        public Nullable<System.DateTime> cEmployee_Level1_Date { get; set; }
        public Nullable<System.DateTime> cEmployee_Level2_Date { get; set; }
        public string cEmployee_Introducer { get; set; }
        public Nullable<bool> cEmployee_IsVegetarian { get; set; }
        public Nullable<System.Guid> cEmployee_ProfitcenterID { get; set; }
        public Nullable<System.Guid> cEmployee_CostCenterID { get; set; }
        public string pk { get; set; }
    }
}
