//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForm_SubContractSeals
    {
        public string cSystem_FormNo { get; set; }
        public Nullable<System.DateTime> cSystem_ApplyDate { get; set; }
        public Nullable<System.DateTime> cSystem_FinishDate { get; set; }
        public string cSystem_MainStatus { get; set; }
        public string cSystem_Status { get; set; }
        public string cSystem_StatusDescription { get; set; }
        public Nullable<bool> cSystem_IsBatchApproval { get; set; }
        public Nullable<bool> cSystem_HasSubmitted { get; set; }
        public string cSystem_TerminateReason { get; set; }
        public string cSystem_ErrorMessage { get; set; }
        public string cApplyUser_EmployeeNO { get; set; }
        public Nullable<System.Guid> cApplyUser_EmployeeID { get; set; }
        public string cApplyUser_Name { get; set; }
        public string cApplyUser_Title { get; set; }
        public Nullable<System.Guid> cApplyUser_DepartmentID { get; set; }
        public string cApplyUser_DepartmentNO { get; set; }
        public string cApplyUser_DepartmentName { get; set; }
        public string cApplyUser_PhoneExt { get; set; }
        public string cApplyUser_WorkPlace { get; set; }
        public string cFillUser_EmployeeNO { get; set; }
        public Nullable<System.Guid> cFillUser_EmployeeID { get; set; }
        public string cFillUser_Name { get; set; }
        public string cFillUser_Title { get; set; }
        public Nullable<System.Guid> cFillUser_DepartmentID { get; set; }
        public string cFillUser_DepartmentNO { get; set; }
        public string cFillUser_DepartmentName { get; set; }
        public string cFillUser_PhoneExt { get; set; }
        public string cFillUser_WorkPlace { get; set; }
        public string cAgentUser_EmployeeNO { get; set; }
        public Nullable<System.Guid> cAgentUser_EmployeeID { get; set; }
        public string cAgentUser_Name { get; set; }
        public string cAgentUser_Title { get; set; }
        public Nullable<System.Guid> cAgentUser_DepartmentID { get; set; }
        public string cAgentUser_DepartmentNO { get; set; }
        public string cAgentUser_DepartmentName { get; set; }
        public string cAgentUser_PhoneExt { get; set; }
        public string cAgentUser_WorkPlace { get; set; }
        public string cContent_ContractID { get; set; }
        public string cContent_CrmOppNo { get; set; }
        public string cContent_CostFormNo { get; set; }
        public string cContent_ContractName { get; set; }
        public string cContent_MainUser_EmployeeNO { get; set; }
        public Nullable<System.Guid> cContent_MainUser_EmployeeID { get; set; }
        public string cContent_MainUser_Name { get; set; }
        public Nullable<System.Guid> cContent_MainUser_DepartmentID { get; set; }
        public string cContent_MainUser_DepartmentName { get; set; }
        public Nullable<decimal> cContent_Amount { get; set; }
        public string cContent_Memo { get; set; }
        public string cContent_ContractInfo_Maintain { get; set; }
        public string cContent_ContractInfo_MakeMoney { get; set; }
        public string cContent_ContractInfo_Note { get; set; }
        public string cContent_ContractInfo_PayNote { get; set; }
        public string cContent_ContractInfo_Address { get; set; }
        public string cContent_ContractInfo_Responses { get; set; }
        public string cContent_ContractInfo_Service { get; set; }
        public string cContent_ContractInfo_Team { get; set; }
        public string cContent_ContractInfo_MainNo { get; set; }
        public string cContent_ContractInfo_MainNoCName { get; set; }
        public string cContent_ContractInfo_Memo { get; set; }
        public string cContent_Secretary { get; set; }
        public string cContent_SecretaryName { get; set; }
        public Nullable<System.Guid> cContent_SecretaryID { get; set; }
        public string cContent_MaintainSales { get; set; }
        public string cContent_MaintainSalesName { get; set; }
        public string cContent_ContractVendor { get; set; }
        public string cContent_ContractUser { get; set; }
        public string cContent_ContractUserID { get; set; }
        public string cContent_ContractDesc { get; set; }
        public string cContent_ContractStrDate { get; set; }
        public string cContent_ContractEndDate { get; set; }
        public string cContent_ContractExtendDate { get; set; }
        public string cContent_ContractPGYear { get; set; }
        public string cContent_ContractPGMonth { get; set; }
        public string cContent_ContractPGOther { get; set; }
        public string cContent_OrigCurrency { get; set; }
        public Nullable<decimal> cContent_OrigAmount { get; set; }
        public string cContent_ExchangeRate { get; set; }
        public Nullable<decimal> cContent_ContractInfo1 { get; set; }
        public Nullable<decimal> cContent_ContractInfo2 { get; set; }
        public string cContent_ContractInfo3_0 { get; set; }
        public string cContent_ContractInfo3 { get; set; }
        public string cContent_ContractInfo3Note { get; set; }
        public string cContent_ContractInfo4 { get; set; }
        public string cContent_ContractInfo5 { get; set; }
        public string cContent_AttatchementId { get; set; }
        public string cContent_ClassifiedLevel { get; set; }
        public string cContent_IsEmptMaintain { get; set; }
        public string cContent_In1CostFormNo { get; set; }
        public string cContent_In1CostItem { get; set; }
        public string cContent_NoMainNo { get; set; }
        public string cContent_InternalNo { get; set; }
        public string cContent_VBELN { get; set; }
        public string cContent_IsDoDraft { get; set; }
        public System.DateTime cSystem_CreatedDate { get; set; }
        public System.Guid cSystem_CreatedUserID { get; set; }
        public string cSystem_CreatedUserName { get; set; }
        public Nullable<System.DateTime> cSystem_ModifiedDate { get; set; }
        public Nullable<System.Guid> cSystem_ModifiedUserID { get; set; }
        public string cSystem_ModifiedUserName { get; set; }
        public string cApplyUser_FullDepartmentName { get; set; }
        public string cFillUser_FullDepartmentName { get; set; }
        public string cAgentUser_FullDepartmentName { get; set; }
        public Nullable<System.DateTime> cSystem_TaskStartDate { get; set; }
        public string cSystem_TaskUserAccounts { get; set; }
        public string cSystem_TaskUserNames { get; set; }
        public string cInheritUser_EmployeeNO { get; set; }
        public string cInheritUser_Name { get; set; }
        public Nullable<System.Guid> cInheritUser_EmployeeID { get; set; }
        public Nullable<System.Guid> cInheritUser_DepartmentID { get; set; }
        public string cInheritUser_DepartmentNO { get; set; }
        public string cInheritUser_DepartmentName { get; set; }
        public string cInheritUser_PhoneExt { get; set; }
        public string cInheritUser_WorkPlace { get; set; }
        public string Content_FormSecretary { get; set; }
        public string Content_FormSecretaryName { get; set; }
        public Nullable<System.Guid> Content_FormSecretaryID { get; set; }
    }
}
