//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_CUSTOMER_WithAddress
    {
        public string KNA1_KUNNR { get; set; }
        public string KNA1_NAME1 { get; set; }
        public string KNVV_VKORG { get; set; }
        public string KNVV_KDGRP { get; set; }
        public string CITY { get; set; }
        public string STREET { get; set; }
        public string TEL { get; set; }
    }
}
