//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_DW_Emp
    {
        public string EmployeeID { get; set; }
        public string Employee { get; set; }
        public string EmpBirthday { get; set; }
        public string EmpSex { get; set; }
        public string EmpSexDesc { get; set; }
        public string EmpADAccount { get; set; }
        public string EmpEmail { get; set; }
        public string EmpRegestDate { get; set; }
        public string DeptID { get; set; }
        public string DeptDesc { get; set; }
        public string EmpTitleDesc { get; set; }
        public string EmpWorkPlace { get; set; }
        public string EmpConstellation { get; set; }
        public string EmpNation { get; set; }
        public string EmpBloodType { get; set; }
        public string EmpLeaveDate { get; set; }
        public string EmpLeaveReason { get; set; }
        public string CompID { get; set; }
        public string Comp { get; set; }
        public string EmpAssignType { get; set; }
        public string EmpAtDesc { get; set; }
        public string EmpIsMarriage { get; set; }
        public Nullable<int> EmpEngReadExam { get; set; }
        public Nullable<int> EmpEngHearExam { get; set; }
        public Nullable<int> EmpEngNewTOEFLExam { get; set; }
        public Nullable<int> EmpEngTOEFLExam { get; set; }
        public Nullable<int> EmpEngTOEICExam { get; set; }
        public string EmpEngIELTSExam { get; set; }
        public string EmpEngGEPTExam { get; set; }
        public Nullable<int> EmpAge { get; set; }
        public string ProfitCenter { get; set; }
        public string ProfitCenterDesc { get; set; }
        public string CostCenter { get; set; }
        public string CostCenterDesc { get; set; }
        public string EmpWorkType { get; set; }
        public string EmpManager { get; set; }
        public string EmpPostseries { get; set; }
        public string JobPost { get; set; }
        public System.DateTime InsertTime { get; set; }
        public string InsertUser { get; set; }
    }
}
