//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSTI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_DEPT_MGR
    {
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string ERP_ID { get; set; }
        public int DEPT_LEVEL { get; set; }
        public int DISABLED { get; set; }
        public string COMP_CODE { get; set; }
        public string UP1_DEPT_ID { get; set; }
        public string UP1_DEPT_NAME { get; set; }
        public string UP1_DEPT_MG_ERP_ID { get; set; }
        public Nullable<int> UP1_LEVEL { get; set; }
        public Nullable<int> UP1_Status { get; set; }
        public string UP2_DPET_ID { get; set; }
        public string UP2_DEPT_NAME { get; set; }
        public string UP2_DEPT_MG_ERP_ID { get; set; }
        public Nullable<int> UP2_LEVEL { get; set; }
        public Nullable<int> UP2_Status { get; set; }
    }
}
